# aad-proxy deployment, service and ingress
# availables at: https://aad.mac-blog.org.ua/
# endpoints: /         - home page will show if you are logged in or not
#            /login    - will redirect to azure login
#            /callback - handle login, verify tokens, extract claims, save cookie, redirect to app
#            /logout   - handle logout, removes cookie and redirect user to app
#            /check    - internal, used by ingress to decide whether user logged in or not
# usage:
# after applying aad-proxy just add following annotations to any ingress you wish to protect:
#
#   nginx.ingress.kubernetes.io/auth-url: "https://aad.mac-blog.org.ua/check"
#   nginx.ingress.kubernetes.io/auth-signin: "https://aad.mac-blog.org.ua/login"
#   nginx.ingress.kubernetes.io/auth-cache-key: $cookie_aad
---
apiVersion: v1
kind: Secret
metadata:
  name: aad-proxy-tls
# Placeholder, used only for further kubectl delete -f kube.yml to delete secret also
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-proxy
  labels:
    app: aad-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aad-proxy
  template:
    metadata:
      labels:
        app: aad-proxy
    spec:
      containers:
        - name: aad-proxy
          image: mac2000/aad-proxy
          env:
            - name: AAD_CLIENT_ID
              value: 3a61a550-0f87-49e5-8511-7bdf3516a055
            - name: AAD_CLIEN_SECRET
              value: ~OE7Q~QARP.khAeplo9a2FYto42Y-gPpCqYH9
            - name: AAD_TENANT_ID
              value: 695e64b5-2d13-4ea8-bb11-a6fda2d60c41
            - name: AAD_CALLBACK_URL
              # domain name of aad-proxy
              value: https://aad.cub.marchenko.net.ua/callback
            - name: AAD_COOKIE_DOMAIN
              # put partent domain name here
              value: cub.marchenko.net.ua
            - name: AAD_COOKIE_NAME
              value: aad
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aad-proxy
spec:
  type: ClusterIP
  selector:
    app: aad-proxy
  ports:
    - name: aad-proxy
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aad-proxy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    # IMPORTANT - azure gives us really big cookies which wont fit into default ingress configs
    # -----------------------------------------------------------------------------------------
    # Fix for: WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
    # Which leads to: Error redeeming code during OAuth2 callback: token exchange failed: oauth2: cannot fetch token: 400 Bad Request
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  tls:
  - hosts:
    - aad.cub.marchenko.net.ua
    secretName: aad-proxy-tls
  rules:
    - host: aad.cub.marchenko.net.ua
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: aad-proxy
                port:
                  number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: app1-tls
# Placeholder, used only for further kubectl delete -f kube.yml to delete secret also
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: nginx:alpine
          ports:
            - name: app1
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: ClusterIP
  selector:
    app: app1
  ports:
    - name: app1
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    # domain name of aad-proxy
    nginx.ingress.kubernetes.io/auth-url: "https://aad.cub.marchenko.net.ua/check"
    nginx.ingress.kubernetes.io/auth-signin: "https://aad.cub.marchenko.net.ua/login"
    # `$cookie_aad`, where `aad` is a cookie name passed via `AAD_COOKIE_NAME` env
    nginx.ingress.kubernetes.io/auth-cache-key: $cookie_aad
spec:
  tls:
  - hosts:
    - app1.cub.marchenko.net.ua
    secretName: app1-tls
  rules:
    - host: app1.cub.marchenko.net.ua
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: app1
                port:
                  number: 80